name: Node.js CI

on:
  push:
    branches: [ main ]   # or your default branch
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]  # or the Node version you want

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run build (if applicable)
      run: npm run build

    - name: Run tests (if applicable)
      run: npm test
